kind: PersistentVolume
apiVersion: v1
metadata:
  name: dummy-back-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/sgumiel/github/docker-tutorial/config/kubernetes"
